issuer: "http://localhost:8080"
port: 8080
upstream_oidc_url: "http://localhost:8081/login"
upstream_jwks_url: "http://localhost:8081/.well-known/jwks.json"
validate_upstream_token: false
signing_key_path: "test/private_key.pem"
token_expires_in: 3600
confidential_clients:
  - client_id: "service-a"
    client_secret: "secret-a"
    audience: "api-service"
public_clients:
  - client_id: "frontend-app"
    audience: "user-profile-api"

telemetry:
  format: "pretty"
  level: "info"
  axum_level: "info"
  sqlx_level: "info"
  service_name: "poltergeist"