apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poltergeist.fullname" . }}-config
  labels:
    {{- include "poltergeist.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.poltergeistConfig | toYaml | nindent 4 }}
