{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poltergeist.fullname" . }}-secret
  labels:
    {{- include "poltergeist.labels" . | nindent 4 }}
type: Opaque
data:
  private_key.pem: {{ .Values.privateKeyPem | b64enc | quote }}
{{- end }}
